"""
Niwa project hosting — generates Caddy config for static sites.
Each deployed project gets served at its slug subdomain.
"""
import json
import os
import sqlite3
import subprocess
from pathlib import Path
from datetime import datetime, timezone

PROJECTS_DIR = Path(os.environ.get("NIWA_PROJECTS_DIR", "/opt/niwatest/data/projects"))
HOSTING_PORT = int(os.environ.get("NIWA_HOSTING_PORT", "8880"))
HOSTING_DOMAIN = os.environ.get("NIWA_HOSTING_DOMAIN", "")
CADDYFILE_PATH = Path(os.environ.get("NIWA_HOSTING_CADDYFILE", "/tmp/niwa-hosting-Caddyfile"))


def _db():
    db_path = os.environ.get("NIWA_DB_PATH", "/data/niwa.sqlite3")
    c = sqlite3.connect(db_path, timeout=10)
    c.row_factory = sqlite3.Row
    c.execute('PRAGMA journal_mode=WAL')
    c.execute('PRAGMA busy_timeout=5000')
    return c


def _ensure_deployments_table():
    c = _db()
    c.execute("""
        CREATE TABLE IF NOT EXISTS deployments (
            id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL,
            slug TEXT NOT NULL UNIQUE,
            directory TEXT NOT NULL,
            url TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            deployed_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)
    c.execute("CREATE INDEX IF NOT EXISTS idx_deployments_project ON deployments(project_id)")
    c.commit()


def generate_caddyfile():
    """Generate Caddyfile from active deployments."""
    c = _db()
    deployments = c.execute("SELECT * FROM deployments WHERE status='active'").fetchall()
    
    lines = [
        "# Auto-generated by Niwa hosting",
        "{",
        "    admin off",
        f"    auto_https off",
        "}",
        "",
    ]
    
    if HOSTING_DOMAIN:
        # Wildcard subdomain routing
        lines.append(f"*.{HOSTING_DOMAIN}:{HOSTING_PORT} {{")
        for d in deployments:
            d = dict(d)
            lines.append(f"    @{d['slug']} host {d['slug']}.{HOSTING_DOMAIN}")
            lines.append(f"    handle @{d['slug']} {{")
            lines.append(f"        root * {d['directory']}")
            lines.append(f"        file_server")
            lines.append(f"        try_files {{path}} /index.html")
            lines.append(f"    }}")
        lines.append("}")
    
    # Always add path-based routing (works without domain)
    lines.append(f":{HOSTING_PORT} {{")
    for d in deployments:
        d = dict(d)
        lines.append(f"    handle_path /{d['slug']}/* {{")
        lines.append(f"        root * {d['directory']}")
        lines.append(f"        file_server")
        lines.append(f"        try_files {{path}} /index.html")
        lines.append(f"    }}")
    # Default: list deployed projects
    lines.append(f"    handle {{")
    lines.append(f'        respond "Niwa Hosting - {len(deployments)} projects deployed" 200')
    lines.append(f"    }}")
    lines.append("}")
    
    CADDYFILE_PATH.write_text("\n".join(lines))
    return str(CADDYFILE_PATH)


def deploy_project(project_id: str, slug: str = "", directory: str = ""):
    """Deploy a project as a static site. Returns deployment info."""
    import uuid
    c = _db()
    project = c.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not project:
        raise ValueError(f"Project not found: {project_id}")
    
    project = dict(project)
    slug = slug or project.get("slug", project_id)
    directory = directory or project.get("directory", str(PROJECTS_DIR / slug))
    
    if not Path(directory).exists():
        raise ValueError(f"Directory not found: {directory}")
    
    now = datetime.now(timezone.utc).isoformat()
    deploy_id = str(uuid.uuid4())
    
    # Check if already deployed
    existing = c.execute("SELECT id FROM deployments WHERE project_id=?", (project_id,)).fetchone()
    if existing:
        c.execute(
            "UPDATE deployments SET slug=?, directory=?, status='active', updated_at=? WHERE project_id=?",
            (slug, directory, now, project_id)
        )
    else:
        c.execute(
            "INSERT INTO deployments (id, project_id, slug, directory, status, deployed_at, updated_at) VALUES (?,?,?,?,?,?,?)",
            (deploy_id, project_id, slug, directory, "active", now, now)
        )
    
    # Build URL
    if HOSTING_DOMAIN:
        url = f"http://{slug}.{HOSTING_DOMAIN}:{HOSTING_PORT}"
    else:
        public_url = os.environ.get("NIWA_PUBLIC_URL", "http://localhost")
        url = f"{public_url}:{HOSTING_PORT}/{slug}/"
    
    # Update deployment URL
    c.execute("UPDATE deployments SET url=? WHERE project_id=?", (url, project_id))
    # Also update project URL
    c.execute("UPDATE projects SET url=?, updated_at=? WHERE id=?", (url, now, project_id))
    c.commit()
    
    # Regenerate Caddy config and reload
    generate_caddyfile()
    _reload_caddy()
    
    return {"url": url, "slug": slug, "directory": directory, "status": "active"}


def undeploy_project(project_id: str):
    c = _db()
    c.execute("UPDATE deployments SET status='inactive', updated_at=? WHERE project_id=?",
              (datetime.now(timezone.utc).isoformat(), project_id))
    c.commit()
    generate_caddyfile()
    _reload_caddy()


def list_deployments():
    c = _db()
    return [dict(r) for r in c.execute("SELECT * FROM deployments WHERE status='active' ORDER BY deployed_at DESC").fetchall()]


def _reload_caddy():
    """Reload or start the hosting Caddy instance.

    NOTE: pkill -USR1 may be silently ignored by Caddy unless it was started
    with --watch. The proper approach is `caddy reload --config <path>` or
    using the Caddy admin API (POST /load). Kept as-is because the fallback
    Docker path below handles most production deployments.
    """
    try:
        # Check if caddy-hosting is running
        r = subprocess.run(["pgrep", "-f", "caddy.*niwa-hosting"], capture_output=True)
        if r.returncode == 0:
            subprocess.run(["pkill", "-USR1", "-f", "caddy.*niwa-hosting"], timeout=5)
        else:
            # Start caddy in background
            subprocess.Popen(
                ["caddy", "run", "--config", str(CADDYFILE_PATH), "--adapter", "caddyfile"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
    except Exception:
        # Caddy might not be installed on host — try docker
        try:
            subprocess.run([
                "docker", "run", "-d", "--rm",
                "--name", "niwa-hosting",
                "-p", f"{HOSTING_PORT}:8880",
                "-v", f"{CADDYFILE_PATH}:/etc/caddy/Caddyfile:ro",
                "-v", f"{str(PROJECTS_DIR)}:{str(PROJECTS_DIR)}:ro",
                "caddy:2-alpine",
            ], capture_output=True, timeout=15)
        except Exception:
            pass

# NOTE: _ensure_deployments_table() removed from module level.
# The deployments table is created by migration 003_deployments.sql.
