"""
Niwa project hosting — generates Caddy config for static sites.
Each deployed project gets served at its slug subdomain.
"""
import json
import os
import sqlite3
import subprocess
from pathlib import Path
from datetime import datetime, timezone

PROJECTS_DIR = Path(os.environ.get("NIWA_PROJECTS_DIR", "/opt/niwatest/data/projects"))
HOSTING_PORT = int(os.environ.get("NIWA_HOSTING_PORT", "8880"))
# Kept only as retro-compat fallback; runtime domain lives in
# ``settings.svc.hosting.domain`` and is read via ``_current_domain()``.
HOSTING_DOMAIN = os.environ.get("NIWA_HOSTING_DOMAIN", "")
CADDYFILE_PATH = Path(os.environ.get("NIWA_HOSTING_CADDYFILE", "/tmp/niwa-hosting-Caddyfile"))


def _db():
    db_path = os.environ.get("NIWA_DB_PATH", "/data/niwa.sqlite3")
    c = sqlite3.connect(db_path, timeout=10)
    c.row_factory = sqlite3.Row
    c.execute('PRAGMA journal_mode=WAL')
    c.execute('PRAGMA busy_timeout=5000')
    return c


def _ensure_deployments_table():
    c = _db()
    c.execute("""
        CREATE TABLE IF NOT EXISTS deployments (
            id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL,
            slug TEXT NOT NULL UNIQUE,
            directory TEXT NOT NULL,
            url TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            deployed_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)
    c.execute("CREATE INDEX IF NOT EXISTS idx_deployments_project ON deployments(project_id)")
    c.commit()


def _current_domain() -> str:
    """Return the live hosting domain.

    Prefers ``settings.svc.hosting.domain`` (set via the wizard); falls
    back to the ``NIWA_HOSTING_DOMAIN`` env var so pre-PR-C2 installs
    keep working until the admin saves a domain from the UI.
    """
    try:
        c = _db()
        row = c.execute(
            "SELECT value FROM settings WHERE key='svc.hosting.domain'"
        ).fetchone()
        if row:
            value = (row["value"] or "").strip()
            if value:
                return value
    except sqlite3.DatabaseError:
        # Settings table may not exist yet during early install.
        pass
    # Read ``NIWA_HOSTING_DOMAIN`` live so systemd env changes take
    # effect on the next Caddyfile regeneration without a reimport.
    return (os.environ.get("NIWA_HOSTING_DOMAIN") or HOSTING_DOMAIN or "").strip()


def generate_caddyfile():
    """Generate Caddyfile from active deployments."""
    c = _db()
    deployments = c.execute("SELECT * FROM deployments WHERE status='active'").fetchall()
    domain = _current_domain()

    lines = [
        "# Auto-generated by Niwa hosting",
        "{",
        "    admin off",
        f"    auto_https off",
        "}",
        "",
    ]

    if domain:
        # Wildcard subdomain routing
        lines.append(f"*.{domain}:{HOSTING_PORT} {{")
        for d in deployments:
            d = dict(d)
            lines.append(f"    @{d['slug']} host {d['slug']}.{domain}")
            lines.append(f"    handle @{d['slug']} {{")
            lines.append(f"        root * {d['directory']}")
            lines.append(f"        file_server")
            lines.append(f"        try_files {{path}} /index.html")
            lines.append(f"    }}")
        lines.append("}")
    
    # Always add path-based routing (works without domain)
    lines.append(f":{HOSTING_PORT} {{")
    for d in deployments:
        d = dict(d)
        lines.append(f"    handle_path /{d['slug']}/* {{")
        lines.append(f"        root * {d['directory']}")
        lines.append(f"        file_server")
        lines.append(f"        try_files {{path}} /index.html")
        lines.append(f"    }}")
    # Default: list deployed projects
    lines.append(f"    handle {{")
    lines.append(f'        respond "Niwa Hosting - {len(deployments)} projects deployed" 200')
    lines.append(f"    }}")
    lines.append("}")
    
    CADDYFILE_PATH.write_text("\n".join(lines))
    return str(CADDYFILE_PATH)


def deploy_project(project_id: str, slug: str = "", directory: str = ""):
    """Deploy a project as a static site. Returns deployment info."""
    import uuid
    c = _db()
    project = c.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not project:
        raise ValueError(f"Project not found: {project_id}")
    
    project = dict(project)
    slug = slug or project.get("slug", project_id)
    directory = directory or project.get("directory", str(PROJECTS_DIR / slug))
    
    if not Path(directory).exists():
        raise ValueError(f"Directory not found: {directory}")
    
    now = datetime.now(timezone.utc).isoformat()
    deploy_id = str(uuid.uuid4())
    
    # Check if already deployed
    existing = c.execute("SELECT id FROM deployments WHERE project_id=?", (project_id,)).fetchone()
    if existing:
        c.execute(
            "UPDATE deployments SET slug=?, directory=?, status='active', updated_at=? WHERE project_id=?",
            (slug, directory, now, project_id)
        )
    else:
        c.execute(
            "INSERT INTO deployments (id, project_id, slug, directory, status, deployed_at, updated_at) VALUES (?,?,?,?,?,?,?)",
            (deploy_id, project_id, slug, directory, "active", now, now)
        )
    
    # Build URL
    domain = _current_domain()
    if domain:
        url = f"http://{slug}.{domain}:{HOSTING_PORT}"
    else:
        public_url = os.environ.get("NIWA_PUBLIC_URL", "http://localhost")
        url = f"{public_url}:{HOSTING_PORT}/{slug}/"
    
    # Update deployment URL
    c.execute("UPDATE deployments SET url=? WHERE project_id=?", (url, project_id))
    # Also update project URL
    c.execute("UPDATE projects SET url=?, updated_at=? WHERE id=?", (url, now, project_id))
    c.commit()
    
    # Regenerate Caddy config and reload
    generate_caddyfile()
    _reload_caddy()
    
    return {"url": url, "slug": slug, "directory": directory, "status": "active"}


def undeploy_project(project_id: str):
    c = _db()
    c.execute("UPDATE deployments SET status='inactive', updated_at=? WHERE project_id=?",
              (datetime.now(timezone.utc).isoformat(), project_id))
    c.commit()
    generate_caddyfile()
    _reload_caddy()


def list_deployments():
    c = _db()
    return [dict(r) for r in c.execute("SELECT * FROM deployments WHERE status='active' ORDER BY deployed_at DESC").fetchall()]


def _detect_public_ip(timeout: float = 3.0):
    """Best-effort public IP detection. Returns None if no echo service
    answers. Used by the hosting wizard to tell the user which IP to put
    in their wildcard DNS record."""
    import ipaddress
    import urllib.request
    for url in ("https://api.ipify.org", "https://ifconfig.me/ip"):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "niwa/0.2"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                ip = r.read().decode().strip()
                try:
                    ipaddress.IPv4Address(ip)
                except ValueError:
                    continue
                return ip
        except Exception:
            continue
    return None


def _is_public_hostname(hostname: str) -> bool:
    """Reject hostnames that would let the ``/api/hosting/status`` probe
    reach internal networks (SSRF defense-in-depth).

    Even though the endpoint is admin-only, the stored ``svc.hosting.domain``
    is free-form text. Rejecting localhost / RFC1918 / link-local / loopback
    keeps the server from being used as a probe against its own cloud
    metadata endpoint or an internal service if an admin typo happens.

    The check requires a syntactic FQDN (contains a ``.`` and is not a bare
    IP) and that *all* resolved A records are public IPs.
    """
    import ipaddress
    h = (hostname or "").strip().lower()
    if not h or "." not in h:
        return False
    # Reject raw IPs (they bypass the FQDN contract anyway).
    try:
        ipaddress.ip_address(h)
        return False
    except ValueError:
        pass
    if h in {"localhost", "localhost.localdomain"}:
        return False
    ips = _resolve_a_records(h)
    if not ips:
        return True  # Unresolvable is fine — we just won't probe successfully.
    for ip_str in ips:
        try:
            ip = ipaddress.ip_address(ip_str)
        except ValueError:
            return False
        # is_reserved is intentionally excluded: TEST-NET-3 (203.0.113.0/24)
        # is marked reserved but is the IETF-standard address for tests.
        # Link-local covers 169.254.169.254 (AWS metadata) which is what
        # actually matters for SSRF defense.
        if (
            ip.is_private
            or ip.is_loopback
            or ip.is_link_local
            or ip.is_multicast
            or ip.is_unspecified
        ):
            return False
    return True


def _resolve_a_records(hostname: str):
    """Return the list of IPv4 addresses the hostname resolves to, or []."""
    import socket
    try:
        infos = socket.getaddrinfo(hostname, None, socket.AF_INET)
        return sorted({info[4][0] for info in infos})
    except Exception:
        return []


def _port_listening(host: str, port: int, timeout: float = 2.0) -> bool:
    import socket
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        s.connect((host, port))
        s.close()
        return True
    except Exception:
        return False


def _http_probe(url: str, timeout: float = 5.0):
    """GET ``url``. Return ``{'ok': bool, 'status': int | None, 'error': str | None}``."""
    import urllib.request
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "niwa-hosting-probe/0.2"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return {"ok": True, "status": int(r.status), "error": None}
    except Exception as e:
        return {"ok": False, "status": None, "error": str(e)}


def get_status() -> dict:
    """Aggregate the hosting configuration + live verification checks.

    Returned shape (intended for the frontend wizard):

        {
            'domain':            str,        # empty if not configured
            'port':              int,
            'public_ip':         str | None, # as seen from outside
            'caddy_listening':   bool,       # 127.0.0.1:<port> open
            'dns':     {'host': str, 'ips': list[str]},
            'wildcard':{'host': str, 'ips': list[str]},
            'http':    {'tried': list[str], 'ok': bool, 'status': int | None,
                        'url': str | None, 'error': str | None},
            'suggested_records': list[dict],
        }

    DNS and HTTP probes are only performed when a domain is configured.
    The function tolerates network failures silently — each field
    degrades to an empty/False value rather than raising.
    """
    c = _db()
    row_domain = c.execute(
        "SELECT value FROM settings WHERE key='svc.hosting.domain'"
    ).fetchone()
    row_port = c.execute(
        "SELECT value FROM settings WHERE key='svc.hosting.port'"
    ).fetchone()
    domain = (row_domain["value"] if row_domain else "").strip()
    try:
        port = int(row_port["value"]) if row_port and row_port["value"] else HOSTING_PORT
    except (ValueError, TypeError):
        port = HOSTING_PORT

    public_ip = _detect_public_ip()
    caddy_listening = _port_listening("127.0.0.1", port)

    result = {
        "domain": domain,
        "port": port,
        "public_ip": public_ip,
        "caddy_listening": caddy_listening,
        "dns": {"host": domain, "ips": []},
        "wildcard": {"host": "", "ips": []},
        "http": {"tried": [], "ok": False, "status": None, "url": None, "error": None},
        "suggested_records": [],
    }

    if domain:
        result["dns"]["ips"] = _resolve_a_records(domain)
        probe_sub = f"niwa-probe.{domain}"
        result["wildcard"] = {
            "host": probe_sub,
            "ips": _resolve_a_records(probe_sub),
        }
        # SSRF defense-in-depth: only HTTP-probe domains whose A records
        # are public IPs. We still return DNS info either way so the
        # wizard can tell the user what's wrong.
        if _is_public_hostname(domain):
            # Probe HTTPS first (Cloudflare proxy default), then plain HTTP.
            tried: list[str] = []
            probe: dict | None = None
            for scheme in ("https", "http"):
                url = f"{scheme}://{domain}/"
                tried.append(url)
                probe = _http_probe(url)
                if probe["ok"]:
                    result["http"] = {
                        "tried": tried,
                        "ok": True,
                        "status": probe["status"],
                        "url": url,
                        "error": None,
                    }
                    break
            else:
                result["http"]["tried"] = tried
                result["http"]["error"] = probe["error"] if probe else None
        else:
            result["http"]["error"] = "private_or_invalid_host"
        if public_ip:
            result["suggested_records"] = [
                {"type": "A", "name": "@", "value": public_ip, "proxied": True},
                {"type": "A", "name": "*", "value": public_ip, "proxied": True},
            ]
    return result


def _reload_caddy():
    """Reload or start the hosting Caddy instance.

    NOTE: pkill -USR1 may be silently ignored by Caddy unless it was started
    with --watch. The proper approach is `caddy reload --config <path>` or
    using the Caddy admin API (POST /load). Kept as-is because the fallback
    Docker path below handles most production deployments.
    """
    try:
        # Check if caddy-hosting is running
        r = subprocess.run(["pgrep", "-f", "caddy.*niwa-hosting"], capture_output=True)
        if r.returncode == 0:
            subprocess.run(["pkill", "-USR1", "-f", "caddy.*niwa-hosting"], timeout=5)
        else:
            # Start caddy in background
            subprocess.Popen(
                ["caddy", "run", "--config", str(CADDYFILE_PATH), "--adapter", "caddyfile"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
    except Exception:
        # Caddy might not be installed on host — try docker
        try:
            subprocess.run([
                "docker", "run", "-d", "--rm",
                "--name", "niwa-hosting",
                "-p", f"{HOSTING_PORT}:8880",
                "-v", f"{CADDYFILE_PATH}:/etc/caddy/Caddyfile:ro",
                "-v", f"{str(PROJECTS_DIR)}:{str(PROJECTS_DIR)}:ro",
                "caddy:2-alpine",
            ], capture_output=True, timeout=15)
        except Exception:
            pass

def _validate_domain(domain: str) -> dict:
    """Run DNS + wildcard + HTTP probes against ``domain``.

    Returns ``{dns_ok, wildcard_ok, http_ok, private}`` where
    ``private`` is True if the domain is a bare IP or resolves to
    RFC1918 / loopback / link-local / multicast (SSRF defense-in-depth,
    parity with ``get_status``). A private / invalid host is a hard
    reject even with ``force=true``.
    """
    private = not _is_public_hostname(domain)
    dns_ips = _resolve_a_records(domain)
    wildcard_ips = _resolve_a_records(f"niwa-probe.{domain}")
    http_ok = False
    if not private:
        for scheme in ("https", "http"):
            probe = _http_probe(f"{scheme}://{domain}/")
            if probe["ok"]:
                http_ok = True
                break
    return {
        "dns_ok": bool(dns_ips),
        "wildcard_ok": bool(wildcard_ips),
        "http_ok": http_ok,
        "private": private,
    }


def save_domain(domain: str, force: bool = False) -> dict:
    """Persist ``svc.hosting.domain`` and regenerate Caddyfile.

    Returns a dict with ``ok``, ``validation`` and ``error``. When the
    domain is a bare IP or resolves privately, we refuse regardless of
    ``force`` and return ``error='private_or_invalid_host'``. Otherwise
    ``force=True`` bypasses DNS / wildcard / HTTP probe failures.

    On success the caller gets a single reload — no retry loop, no
    partial state.
    """
    clean = (domain or "").strip().lower()
    if not clean:
        return {"ok": False, "error": "domain_required", "validation": None}

    validation = _validate_domain(clean)
    if validation["private"]:
        return {
            "ok": False,
            "error": "private_or_invalid_host",
            "validation": {
                "dns_ok": validation["dns_ok"],
                "wildcard_ok": validation["wildcard_ok"],
                "http_ok": validation["http_ok"],
            },
        }
    probes_ok = (
        validation["dns_ok"]
        and validation["wildcard_ok"]
        and validation["http_ok"]
    )
    if not probes_ok and not force:
        return {
            "ok": False,
            "error": "validation_failed",
            "validation": {
                "dns_ok": validation["dns_ok"],
                "wildcard_ok": validation["wildcard_ok"],
                "http_ok": validation["http_ok"],
            },
        }

    c = _db()
    c.execute(
        "INSERT INTO settings (key, value) VALUES ('svc.hosting.domain', ?) "
        "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
        (clean,),
    )
    c.commit()
    generate_caddyfile()
    _reload_caddy()
    return {
        "ok": True,
        "error": None,
        "domain": clean,
        "validation": {
            "dns_ok": validation["dns_ok"],
            "wildcard_ok": validation["wildcard_ok"],
            "http_ok": validation["http_ok"],
        },
    }


def clear_domain() -> dict:
    """Remove the stored hosting domain and regenerate the Caddyfile.

    Leaves any ``NIWA_HOSTING_DOMAIN`` env fallback untouched — callers
    that want a fully unbranded setup must also unset the env var.
    """
    c = _db()
    c.execute("DELETE FROM settings WHERE key='svc.hosting.domain'")
    c.commit()
    generate_caddyfile()
    _reload_caddy()
    return {"ok": True}


# NOTE: _ensure_deployments_table() removed from module level.
# The deployments table is created by migration 003_deployments.sql.
