-- Migration 016: routines.improvement_type + deployments.consecutive_failures (PR-C3)
--
-- Adds two columns needed for the ``product_healthcheck`` seed routine
-- and for PR-C4 (_exec_improve with functional|stability|security
-- templates):
--
--  1. ``routines.improvement_type`` — nullable TEXT, populated only when
--     ``action='improve'``. Values enforced at the HTTP layer:
--     ``{'functional','stability','security'}``.
--  2. ``deployments.consecutive_failures`` — INTEGER NOT NULL DEFAULT 0,
--     used by the product_healthcheck loop to accumulate strikes across
--     ticks. When it reaches 3, a fix task is created and the counter is
--     frozen at 3 until a successful HTTP probe resets it.
--
-- Note on CHECK constraints: SQLite cannot ALTER a CHECK constraint in
-- place. The ``routines.action`` CHECK in ``schema.sql`` is updated to
-- include ``'improve'`` for fresh installs. For migrated DBs the pre-016
-- CHECK stays, and ``'improve'`` is enforced via the HTTP layer +
-- ``scheduler.create_routine()``/``update_routine()`` whitelist. Same
-- pattern used by migration 015 for ``projects.autonomy_mode``.
ALTER TABLE routines ADD COLUMN improvement_type TEXT;
ALTER TABLE deployments ADD COLUMN consecutive_failures INTEGER NOT NULL DEFAULT 0;
